name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  python-tests:
    uses: Testingland-R/workflows/.github/workflows/pytest-scan.yml@ff7ff1bf91fe1552e5db641c55c896f97b37e436 # main
    with:
      python-version: '3.11'
      test-command: 'pytest --maxfail=1 --cov=. --cov-report=xml -v'

  sonarqube-scan:
    needs: python-tests
    uses: Testingland-R/workflows/.github/workflows/sonarqube-scan.yml@ff7ff1bf91fe1552e5db641c55c896f97b37e436 # main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    with:
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
