name: Renovate auto approve call

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [dismissed]


jobs:
  Aprover_call:
    uses: Testingland-R/workflows/.github/workflows/renovate-auto-approve.yml@ff7ff1bf91fe1552e5db641c55c896f97b37e436 # main
    permissions:
      pull-requests: write
      contents: read
